### PR TITLE
added function to set reference

### PR DESCRIPTION
**Pull request by mtzm**

### CODE REVIEW

**Comment by Molorius** [comment]
This looks good, but it should match the style of the rest of the project and should be documented in the README. The documentation can just be a brief description of the function and what the input parameters can be. The parameters can be found here: https://github.com/Molorius/ADS126X/blob/ea78ce2be0bdcf9058228b1ad41768a24c3d2f83/src/definitions/ADS126X_definitions.h#L181-L191
I can just merge and add the changes myself if you would like.

**Comment by mtzm** [comment]
I added the documentation

**Comment by q-bird** [comment]
Hi @mtzm 
Your contribution is very useful!
BTW, Can you consider to implement the function of setup IDAC1 and IDAC2 with the value from 50uA-3000uA?
Thank you

**Comment by Molorius** [comment]
Thank you for your contribution mtzm, I'm merging it now.

q-bird, you don't need to hijack a pull request. You have an issue posted, so people can already see that it's a wanted feature.

**Pull request merged**
